/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.upeu.sysventas;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import java.util.TimeZone;
/**
 *
 * @author AngelRC2
 */
public class frmVenta extends javax.swing.JFrame {   
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmVenta.class.getName());
    //Varibales para cargar la fecha y hora en español
    java.util.Calendar calendario; 
    int dia, dias, mes, año, hora, hora24, minutos, segundos, meridiano;
    String fecha,horaActual;
    //Variable conectar a la base datos
    private Connection conn;
    //Varibales para manejar tabla de busqueda de productos
    private DefaultTableModel modeloProd;
    private int idSeleccionadoProd = -1;
    //Variables para manejar tabla de detalle de venta
    DefaultTableModel modeloDetalle;
    //Par imprimir vooucher
    private int idVenta;
    /**
     * Creates new form frmVenta
     */
    public frmVenta() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); //X2
        reloj();
        conectar();
        cargarProductos("");
        modeloDetalle= new DefaultTableModel(new String[]{"ID", "Nombre", "Cantidad","Precio","Importe"}, 0);
        tbldetalle.setModel(modeloDetalle);
        conectar();
        crearTablas();
        btnImprimirVenta.setEnabled(false);
        btnNuevaVenta.setEnabled(false);
    }
    
    private void conectar() {
        conn = Conexion.getConexion();
    }
        
    private void cargarProductos(String nombre){
        modeloProd = new DefaultTableModel(new String[]{"ID", "Nombre", "Cantidad","Precio","Código"}, 0);
        tblproductos.setModel(modeloProd);
        modeloProd.setRowCount(0);
        try (Statement stmt = conn.createStatement();
            //String sql = "SELECT * FROM productos WHERE nombre LIKE ?";
            ResultSet rs = stmt.executeQuery("SELECT * FROM productos WHERE nombre LIKE '%"+nombre+"%'")) {

            while (rs.next()) {
                modeloProd.addRow(new Object[]{
                        rs.getInt("id"),
                        rs.getString("nombre"),
                        rs.getString("cantidad"),
                        rs.getString("precio"),
                        rs.getString("codigo")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarClienteAPI = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        btnBuscarClienteDB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblhora = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtnombreprod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproductos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbldetalle = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtproducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtimporte = new javax.swing.JTextField();
        btnAgregarDetalle = new javax.swing.JButton();
        btnQuitarDetalle = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtigv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        lblNumeroLetras = new javax.swing.JLabel();
        btnNuevaVenta = new javax.swing.JButton();
        btnGrabarVenta = new javax.swing.JButton();
        btnImprimirVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true), "Buscar cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("DNI(*)");

        txtdni.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setText("Nombre y apellidos (*)");

        btnBuscarClienteAPI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PNG-24/Search.png"))); // NOI18N
        btnBuscarClienteAPI.setText("Buscar AIPI");
        btnBuscarClienteAPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteAPIActionPerformed(evt);
            }
        });

        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PNG-24/Add.png"))); // NOI18N
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        btnBuscarClienteDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PNG-24/Search.png"))); // NOI18N
        btnBuscarClienteDB.setText("Buscar BD");
        btnBuscarClienteDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtdni, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBuscarClienteAPI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnBuscarClienteDB)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarCliente)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarCliente)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarClienteAPI)
                    .addComponent(btnBuscarClienteDB))
                .addGap(64, 64, 64))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        lblhora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("NOTA DE VENTA");

        lblfecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)), "Buscar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        txtnombreprod.setBackground(new java.awt.Color(255, 255, 204));
        txtnombreprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreprodKeyPressed(evt);
            }
        });

        tblproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Precio", "Código"
            }
        ));
        tblproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblproductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblproductos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombreprod, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtnombreprod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)), "Detalle de venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        tbldetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Precio", "Importe"
            }
        ));
        jScrollPane2.setViewportView(tbldetalle);

        jLabel4.setText("ID");

        jLabel5.setText("Producto");

        jLabel6.setText("Precio");

        jLabel7.setText("Cantidad(*)");

        txtcantidad.setBackground(new java.awt.Color(255, 255, 204));
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcantidadKeyPressed(evt);
            }
        });

        jLabel8.setText("Importe");

        btnAgregarDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PNG-24/Next.png"))); // NOI18N
        btnAgregarDetalle.setText("Agregar");
        btnAgregarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDetalleActionPerformed(evt);
            }
        });

        btnQuitarDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PNG-24/Delete.png"))); // NOI18N
        btnQuitarDetalle.setText("Quitar");
        btnQuitarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarDetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel7)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel8))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtimporte, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuitarDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid)
                            .addComponent(txtproducto)
                            .addComponent(txtprecio)
                            .addComponent(txtcantidad)
                            .addComponent(txtimporte)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuitarDetalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Subtotal");

        txtsubtotal.setBackground(new java.awt.Color(204, 204, 204));
        txtsubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtsubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("IGV 18%");

        txtigv.setBackground(new java.awt.Color(204, 204, 204));
        txtigv.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtigv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Total");

        txttotal.setBackground(new java.awt.Color(204, 204, 204));
        txttotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txttotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txttotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtigv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtigv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)))
        );

        lblNumeroLetras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNumeroLetras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroLetras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PNG-32/Modify.png"))); // NOI18N
        btnNuevaVenta.setText("Nueva Venta");
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });

        btnGrabarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PNG-32/Load.png"))); // NOI18N
        btnGrabarVenta.setText("Grabar Venta");
        btnGrabarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarVentaActionPerformed(evt);
            }
        });

        btnImprimirVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/PNG-32/Print.png"))); // NOI18N
        btnImprimirVenta.setText("Imprimir");
        btnImprimirVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumeroLetras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGrabarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnImprimirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 956, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumeroLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGrabarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImprimirVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteAPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteAPIActionPerformed
        String dni=txtdni.getText();
        if (dni.length()!=8) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese 8 digitos del DNI");
        }else{
            String nombreCliente = ConsultaDNI.obtenerNombrePorDNI(dni);
            txtnombre.setText(nombreCliente);
        }
        
    }//GEN-LAST:event_btnBuscarClienteAPIActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        new frmClientes().show();
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnBuscarClienteDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarClienteDBActionPerformed

    private void txtnombreprodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreprodKeyPressed
        String producto=txtnombreprod.getText();
        cargarProductos(producto);
        
    }//GEN-LAST:event_txtnombreprodKeyPressed

    private void tblproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblproductosMouseClicked
        int fila=tblproductos.getSelectedRow();        
        String id=modeloProd.getValueAt(fila, 0).toString();
        String nombre=modeloProd.getValueAt(fila, 1).toString();
        //String cantidad=modeloProd.getValueAt(fila, 2).toString();
        String precio=modeloProd.getValueAt(fila, 3).toString();
        //String codigo=modeloProd.getValueAt(fila, 4).toString();
        txtid.setText(id);
        txtproducto.setText(nombre);
        txtcantidad.setText("1");
        txtprecio.setText(precio);        
        txtimporte.setText(precio);
        
    }//GEN-LAST:event_tblproductosMouseClicked

    private void btnAgregarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDetalleActionPerformed
        //Agregar producto al detalle de comprobante
        String id=txtid.getText();
        String nombre=txtproducto.getText();
        String cantidad=txtcantidad.getText();
        String precio=txtprecio.getText();
        String importe=txtimporte.getText();
        Object[]newRow ={id,nombre,cantidad,precio,importe};
        modeloDetalle.addRow(newRow); 
        
        //Caluclar subtotal, igv y total
        modeloDetalle = (DefaultTableModel) tbldetalle.getModel();
        double total = 0.0;

        for (int i = 0; i < modeloDetalle.getRowCount(); i++) {
            String valorCelda = modeloDetalle.getValueAt(i, 4).toString(); // columna 3 = importe
            try {
                double importedet = Double.parseDouble(valorCelda);
                total += importedet;
            } catch (NumberFormatException e) {
                // Si no se puede convertir, ignora o muestra advertencia
                System.err.println("Valor no numérico en la fila " + i + ": " + valorCelda);
            }
        }
        double subtotal=total/1.18;
        double igv= total-subtotal;
        txttotal.setText(String.format("%.2f", total));
        txtsubtotal.setText(String.format("%.2f",subtotal));
        txtigv.setText(String.format("%.2f", igv));
        //Usamos la clase con el metodo  convertir para pasar el total a letras
        String totalEnLetras=NumeroALetras.convertir(total);
        lblNumeroLetras.setText(totalEnLetras);
    }//GEN-LAST:event_btnAgregarDetalleActionPerformed

    private void txtcantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            String cantidad=txtcantidad.getText();
            if(isNumeric(cantidad) && cantidad.length()>=1 && Integer.parseInt(cantidad)>=1){
                String precio=txtprecio.getText();
                double subtotal=Double.parseDouble(cantidad)*Double.parseDouble(precio);
                txtimporte.setText(String.valueOf(subtotal));
            }else{
                JOptionPane.showMessageDialog(rootPane,"La cantidad minima debe ser 1");
            }
        }
    }//GEN-LAST:event_txtcantidadKeyPressed

    private void btnQuitarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarDetalleActionPerformed
        if (tbldetalle.getSelectedRowCount()==1) {
            modeloDetalle.removeRow(tbldetalle.getSelectedRow());
        }else{
            if(tbldetalle.getRowCount()==0){
                JOptionPane.showMessageDialog(rootPane, "La tabla esta vacia");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Selecione una sola fila");
            }
        }
    }//GEN-LAST:event_btnQuitarDetalleActionPerformed

    private void btnGrabarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarVentaActionPerformed
        String sqlVenta = "INSERT INTO ventas (dni_cliente, nombre_cliente, fecha, hora, subtotal, igv, total, tletras) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement psVenta=null;
        try {
            psVenta = conn.prepareStatement(sqlVenta, Statement.RETURN_GENERATED_KEYS);
            psVenta.setString(1, txtdni.getText());
            psVenta.setString(2, txtnombre.getText());
            Calendar calendario = new GregorianCalendar(TimeZone.getTimeZone("America/Lima"));
            String fecha = String.format("%04d-%02d-%02d",
                    calendario.get(Calendar.YEAR),
                    calendario.get(Calendar.MONTH) + 1,
                    calendario.get(Calendar.DAY_OF_MONTH));
            String hora = String.format("%02d:%02d:%02d",
                    calendario.get(Calendar.HOUR_OF_DAY),
                    calendario.get(Calendar.MINUTE),
                    calendario.get(Calendar.SECOND));
            psVenta.setString(3, fecha);
            psVenta.setString(4, hora);
            psVenta.setDouble(5, Double.parseDouble(txtsubtotal.getText()));
            psVenta.setDouble(6, Double.parseDouble(txtigv.getText()));
            psVenta.setDouble(7, Double.parseDouble(txttotal.getText()));
            psVenta.setString(8, lblNumeroLetras.getText());

            psVenta.executeUpdate();

            // Obtener ID generado
            ResultSet rsVenta = psVenta.getGeneratedKeys();
            idVenta = 0;
            if (rsVenta.next()) {
                idVenta = rsVenta.getInt(1);
            }
            //Insertar detalles desde modeloDetalle
            //DefaultTableModel modeloDetalle = (DefaultTableModel) tbldetalle.getModel();
            String sqlActualizarCantidad = "UPDATE productos SET cantidad = cantidad - ? WHERE id = ?";
            PreparedStatement psActualizarCantidad = conn.prepareStatement(sqlActualizarCantidad);


            for (int i = 0; i < modeloDetalle.getRowCount(); i++) {
                //Actualizar cantidad de productos           
                int cantidadVendida = Integer.parseInt(modeloDetalle.getValueAt(i, 2).toString());               
                psActualizarCantidad.setString(1, String.valueOf(cantidadVendida)); // cantidad                   
                psActualizarCantidad.setString(2, modeloDetalle.getValueAt(i, 0).toString()); //id
                psActualizarCantidad.executeUpdate();

            }
            btnGrabarVenta.setEnabled(false);
            btnImprimirVenta.setEnabled(true);
            btnNuevaVenta.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Venta registrada correctamente.");

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_btnGrabarVentaActionPerformed

    private void btnImprimirVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirVentaActionPerformed
        PreparedStatement psVenta = null, psDetalle = null;
    ResultSet rsVenta = null, rsDetalle = null;

    try {
        // Consulta la venta
        String sqlVenta = "SELECT * FROM ventas WHERE id = ?";
        psVenta = conn.prepareStatement(sqlVenta);
        psVenta.setInt(1, idVenta);
        rsVenta = psVenta.executeQuery();

        if (!rsVenta.next()) {
            JOptionPane.showMessageDialog(rootPane, "Venta no encontrada");
            return;
        }

        String voucher = "   CAFE & CANELA\n";
        voucher += " Real Plaza - Juliaca\n";
        voucher += "------------------------------\n";

        int idVenta = rsVenta.getInt("id");
        String idFormateado = "E" + String.format("%05d", idVenta);
        voucher = "       NOTA #" + idFormateado + "\n";
        voucher += "------------------------------------------\n";
        voucher += "Cliente: " + rsVenta.getString("nombre_cliente") + "\n";
        voucher += "DNI: " + rsVenta.getString("dni_cliente") + "\n";
        voucher += "Fecha: " + rsVenta.getString("fecha") + "  Hora: " + rsVenta.getString("hora") + "\n";
        voucher += "------------------------------------------\n";
        voucher += "Producto       Cant Precio   Importe\n";

        // Consulta detalle de venta
        String sqlDetalle = "SELECT * FROM detalle_venta WHERE id_venta = ?";
        psDetalle = conn.prepareStatement(sqlDetalle);
        psDetalle.setInt(1, idVenta);
        rsDetalle = psDetalle.executeQuery();

        while (rsDetalle.next()) {
            String producto = rsDetalle.getString("nombre");
            int cantidad = rsDetalle.getInt("cantidad");
            double precio = rsDetalle.getDouble("precio");
            double importe = rsDetalle.getDouble("importe");

            if (producto.length() > 14) producto = producto.substring(0, 14);
            voucher += String.format("%-14s %3d %6.2f %9.2f\n", producto, cantidad, precio, importe);
        }

        voucher += "------------------------------\n";
        voucher += String.format("Subtotal: S/ %.2f\n", rsVenta.getDouble("subtotal"));
        voucher += String.format("IGV:      S/ %.2f\n", rsVenta.getDouble("igv"));
        voucher += String.format("Total:    S/ %.2f\n", rsVenta.getDouble("total"));
        voucher += "\n  Gracias por su compra!\n\n\n";

        // Imprime el voucher
        ImpresoraPOS.imprimirVoucher(voucher);
        JOptionPane.showMessageDialog(rootPane, "Voucher imprimido");

        // 🔁 Refresca interfaz para nueva venta
        reiniciarFormulario();

    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        try {
            if (rsVenta != null) rsVenta.close();
            if (psVenta != null) psVenta.close();
            if (rsDetalle != null) rsDetalle.close();
            if (psDetalle != null) psDetalle.close();
            // ❌ NO cerrar conn aquí
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    }//GEN-LAST:event_btnImprimirVentaActionPerformed

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        // Limpiar inputs
        txtdni.setText("");
        txtnombre.setText("");
        txtsubtotal.setText("");
        txtigv.setText("");
        txttotal.setText("");
        txtid.setText("");
        txtproducto.setText("");
        txtcantidad.setText("");
        txtprecio.setText("");

        // Limpiar tablas
        modeloDetalle.setRowCount(0);
       
        // Desactivar botón Imprimir
        btnImprimirVenta.setEnabled(false);
        btnNuevaVenta.setEnabled(false);
        //Activar boton para grabar
        btnGrabarVenta.setEnabled(true);
    }//GEN-LAST:event_btnNuevaVentaActionPerformed
    
    private boolean isNumeric(String text) {
        for (char c : text.toCharArray()) {
            if (!Character.isDigit(c)) {
                return false;
            }
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        // Ejecutar aplicación
        SwingUtilities.invokeLater(() -> new frmVenta());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmVenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarDetalle;
    private javax.swing.JButton btnBuscarClienteAPI;
    private javax.swing.JButton btnBuscarClienteDB;
    private javax.swing.JButton btnGrabarVenta;
    private javax.swing.JButton btnImprimirVenta;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnQuitarDetalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNumeroLetras;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhora;
    private javax.swing.JTable tbldetalle;
    private javax.swing.JTable tblproductos;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtigv;
    private javax.swing.JTextField txtimporte;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombreprod;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtproducto;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
    
    private void reloj() { 
        TimeZone tzPeru = TimeZone.getTimeZone("America/Lima");
        calendario = new java.util.GregorianCalendar(tzPeru); 
        segundos = calendario.get(Calendar.SECOND); 
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() { 
        @ Override 
        public void actionPerformed(java.awt.event.ActionEvent ae) { 
            java.util.Date actual = new java.util.Date(); 
            calendario.setTime(actual); 
            dia = calendario.get(Calendar.DAY_OF_MONTH); 
            dias=calendario.get(Calendar.DAY_OF_WEEK);
            mes = (calendario.get(Calendar.MONTH) + 1); 
            año = calendario.get(Calendar.YEAR); 
            hora = calendario.get(Calendar.HOUR);
            hora24 = calendario.get(Calendar.HOUR_OF_DAY);
            minutos = calendario.get(Calendar.MINUTE); 
            segundos = calendario.get(Calendar.SECOND); 
            meridiano=calendario.get(Calendar.AM_PM);
            String m=(meridiano==0)?"AM":"PM";
            //JOptionPane.showMessageDialog(rootPane, m);            
            String hour = String.format("%02d : %02d : %02d %s", hora24, minutos, segundos, m); 
            String date = String.format("%s, %02d de %s del %02d",Funciones.diaLetras(String.valueOf(dias)), dia, Funciones.mesLetras(String.valueOf(mes)), año); 
            lblhora.setText("<html><center>" +hour+"</center></html>"); 
            lblfecha.setText("<html><p>"+date+"</p></html>");
            fecha=String.format("%04d-%02d-%02d",año,mes,dias);
            horaActual=hour;
            
        } 
        }); 
        timer.start(); 
    }
    //Crear tabla si no existe
    private void crearTablas() {
        try (Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS ventas (" +
                    "id INTEGER PRIMARY KEY AUTOINCREMENT," +
                    "dni_cliente TEXT," +
                    "nombre_cliente TEXT," +
                    "fecha TEXT," +
                    "hora TEXT," +
                    "subtotal REAL," +
                    "igv REAL," +
                    "tletras TEXT," +
                    "total REAL)");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al crear tabla: " + e.getMessage());
        }
        // Crear tabla detalle_venta
        try (Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE IF NOT EXISTS detalle_venta (" +
                    "id INTEGER PRIMARY KEY AUTOINCREMENT," +
                    "id_venta INTEGER," +
                    "id_producto TEXT," +
                    "nombre TEXT," +
                    "cantidad REAL," +
                    "precio INTEGER," +
                    "importe TEXT," +
                    "FOREIGN KEY(id_venta) REFERENCES ventas(id))");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al crear tabla: " + e.getMessage());
        }
    }
    private void reiniciarFormulario() {
    cargarProductos(""); // 🔁 Actualiza la tabla de productos
    modeloDetalle.setRowCount(0); // 🧹 Limpia el detalle
    txtdni.setText("");
    txtnombre.setText("");
    txtsubtotal.setText("");
    txtigv.setText("");
    txttotal.setText("");
    txtid.setText("");
    txtproducto.setText("");
    txtcantidad.setText("");
    txtprecio.setText("");
    txtimporte.setText("");
    lblNumeroLetras.setText("");
    btnImprimirVenta.setEnabled(false);
    btnNuevaVenta.setEnabled(false);
    btnGrabarVenta.setEnabled(true);
}

}

