/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.upeu.sysventas;
import javax.print.*;
import java.io.*;
/**
 *
 * @author Datos
 */
public class Impresora extends javax.swing.JFrame {

    /**
     * Creates new form Impresora
     */
    public Impresora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Voucher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver impresoras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Buscar impresora por nombre (reemplaza si deseas una específica)
            PrintService[] services = PrintServiceLookup.lookupPrintServices(null, null);
            PrintService printService = null;
            for (PrintService service : services) {
                if (service.getName().equalsIgnoreCase("POS-80-Series")) {
                    printService = service;
                    break;
                }
            }
            if (printService == null) {
                System.out.println("No se encontró la impresora POS.");
                return;
            }


            // Crear un flujo de datos con comandos ESC/POS
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

            // Comandos ESC/POS comunes
            final byte[] ESC_ALIGN_CENTER = new byte[]{0x1B, 'a', 0x01};
            final byte[] ESC_ALIGN_LEFT = new byte[]{0x1B, 'a', 0x00};
            final byte[] ESC_BOLD_ON = new byte[]{0x1B, 0x45, 0x01};
            final byte[] ESC_BOLD_OFF = new byte[]{0x1B, 0x45, 0x00};
            final byte[] ESC_CUT = new byte[]{0x1D, 'V', 0x42, 0x00};

            // Imprimir encabezado centrado
            outputStream.write(ESC_ALIGN_CENTER);
            outputStream.write(ESC_BOLD_ON);
            outputStream.write("TIENDA EL ÉXITO\n".getBytes("UTF-8"));
            outputStream.write(ESC_BOLD_OFF);
            outputStream.write("Av. Principal 123 - Puno\n".getBytes("UTF-8"));
            outputStream.write("--------------------------------\n".getBytes("UTF-8"));

            // Detalles de venta alineados a la izquierda
            outputStream.write(ESC_ALIGN_LEFT);
            outputStream.write("Venta N°: 000123\n".getBytes("UTF-8"));
            outputStream.write("Fecha: 2025-06-09 10:30\n".getBytes("UTF-8"));
            outputStream.write("--------------------------------\n".getBytes("UTF-8"));
            outputStream.write("Producto       Cant  Precio\n".getBytes("UTF-8"));
            outputStream.write("Panetón        2     S/50.00\n".getBytes("UTF-8"));
            outputStream.write("Chocolate      1     S/10.00\n".getBytes("UTF-8"));
            outputStream.write("--------------------------------\n".getBytes("UTF-8"));
            outputStream.write("TOTAL A PAGAR:     S/60.00\n".getBytes("UTF-8"));

            // Mensaje final
            outputStream.write(ESC_ALIGN_CENTER);
            outputStream.write("¡Gracias por su compra!\n".getBytes("UTF-8"));

            // Espacios y corte de papel
            outputStream.write("\n\n\n".getBytes("UTF-8"));
            outputStream.write(ESC_CUT);

            // Crear flujo de entrada desde los datos generados
            InputStream inputStream = new ByteArrayInputStream(outputStream.toByteArray());

            // Enviar a la impresora
            DocFlavor flavor = DocFlavor.INPUT_STREAM.AUTOSENSE;
            Doc doc = new SimpleDoc(inputStream, flavor, null);
            DocPrintJob job = printService.createPrintJob();
            job.print(doc, null);

            System.out.println("Voucher impreso correctamente.");
        } catch (Exception e) {
            System.out.println("Error al imprimir: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PrintService[] printServices = PrintServiceLookup.lookupPrintServices(null, null);
        System.out.println("Impresoras disponibles:");
        for (PrintService printer : printServices) {
            System.out.println(" - " + printer.getName());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Impresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Impresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Impresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Impresora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impresora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
